### ISSUE TITLE
关于mobileone推理部分如何在训练的时候设置参数的问题？

### ISSUE THREAD

**Issue by HGS-1998** [civat/DL-Theory-Practice#2]
作者你好，我在看你源码部署时，不太懂如何来在验证的时候使用推理部分的模型，请您帮助我，谢谢！

**Comment by civat** [comment]
能详细描述一下问题吗？

**Comment by HGS-1998** [comment]
> 能详细描述一下问题吗？

谢谢你的回复，大概意思是：在看您的MobileOne代码时，用数据集进行训练的时候，使用的是deploy=False，就是使用重参数的模型，没有使用推理的模型，如何在测试的时候，用到推理的模型，直接把deploy=True,就可以吗？

**Comment by HGS-1998** [comment]
> 能详细描述一下问题吗？

仅仅使用model.eval()，似乎并不能将deploy=True传递进去？对此，我很迷茫，请求你的帮助？

**Comment by civat** [comment]
同model.eval()没有关系。 
在训练阶段，只需在配置文件中设置deploy=True（示例config应该是deploy=True），那么模型在训练完毕后会进行重参数化，并把重参数化后的模型存储下来。
如果你想把重参数化后的模型重新读进来，去做推理，那么最简单的做法是：
你用训练时的Config文件去初始化一个MobileOne模型，然后再对模型调用.deploy()，最后再加载参数即可。

**Comment by civat** [comment]
done
